apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-org2-peer0
  namespace: org2-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: joinchannel-peer0-join-allchannel-org2-peer0
  chart:
    git: git@github.com:bafazureuser2/blockchain-automation-framework.git
    ref: feature/fabric220
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: org2-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.org2-net.org2.cluster2.pslblockchaincloudpoc.com:8443
      localmspid: org2MSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vaultserver.eastus.cloudapp.azure.com:10200
      authpath: org2-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/org2-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/org2-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.ordererorg.cluster1.pslblockchaincloudpoc.com:8443

